// packages/squircle-element-react/src/StaticSquircle.tsx
import { Slot } from "@radix-ui/react-slot";
import { getSvgPath } from "figma-squircle";
import type { ComponentPropsWithoutRef, PropsWithChildren } from "react";
import { useMemo } from "react";

interface StaticSquircleProps {
  asChild?: boolean;

  width: number;
  height: number;
  cornerRadius: number;
  cornerSmoothing: number;
}

export const StaticSquircle = ({
  asChild,
  width,
  height,
  cornerRadius,
  cornerSmoothing,
  style,
  ...props
}: PropsWithChildren<
  StaticSquircleProps & ComponentPropsWithoutRef<"div">
>) => {
  const Component = asChild ? Slot : "div";

  const path = useMemo(() => {
    return getSvgPath({
      width,
      height,
      cornerRadius,
      cornerSmoothing,
    });
  }, [width, height, cornerRadius, cornerSmoothing]);

  return (
    <Component style={{ clipPath: `path('${path}')`, ...style }} {...props} />
  );
};

// packages/squircle-element-vue/src/StaticSquircle.vue
<script lang="ts">
export interface StaticSquircleProps {
    /**
     * The element or component this component should render as when not a div.
     * @defaultValue 'div'
     */
    as?: any;
    cornerSmoothing?: number;
    cornerRadius?: number;
    width?: number;
    height?: number;
}

export interface StaticSquircleSlots {
    default(props?: {}): any;
}
</script>

<script setup lang="ts">
import { computed, useTemplateRef } from 'vue';
import { getSvgPath } from 'figma-squircle';
import { useElementSize } from '@vueuse/core';

const props = withDefaults(defineProps<StaticSquircleProps>(), {
    as: 'div',
    cornerSmoothing: 0.6
});
defineSlots<StaticSquircleSlots>();

const el = useTemplateRef<HTMLDivElement>('el');
const { width, height } = useElementSize(el);

const path = computed(() => getSvgPath({
        width: width.value,
        height: height.value,
        cornerRadius: props.cornerRadius,
        cornerSmoothing: props.cornerSmoothing
    })
);
</script>

<template>
    <component
        :is="as"
        ref="el"
        v-bind="props"
        :style="{
            borderRadius: cornerRadius,
            width: width,
            height: height,
            clipPath: `path('${path}')`,
        }"
        :data-squircle="cornerRadius"
    >
        <slot />
    </component>
</template>
