// apps/examples-vue/src/examples/Avatar.vue
<script setup lang="ts">
import { staticSquircleDirective as vStaticSquircle } from "@squircle-js/vue";

const props = withDefaults(
  defineProps<{ src: string; alt: string; size?: number }>(),
  { size: 48 },
);
</script>

<template>
  <img
    :src="src"
    :alt="alt"
    v-static-squircle="{
      width: props.size,
      height: props.size,
      cornerRadius: Math.round(props.size * 0.25),
      cornerSmoothing: 0.6,
    }"
    class="object-cover shrink-0"
  />
</template>

// apps/examples-svelte/src/examples/Avatar.svelte
<script lang="ts">
  import { staticSquircle } from "@squircle-js/svelte";

  let { src, alt, size = 48 } = $props<{
    src: string;
    alt: string;
    size?: number;
  }>();
</script>

<img
  {src}
  {alt}
  use:staticSquircle={{
    width: size,
    height: size,
    cornerRadius: Math.round(size * 0.25),
    cornerSmoothing: 0.6,
  }}
  class="object-cover shrink-0"
/>
