// apps/examples-vue/src/examples/ImageContainer.vue
<script setup lang="ts">
import { staticSquircleDirective as vStaticSquircle } from "@squircle-js/vue";

defineProps<{ src: string; alt: string }>();
</script>

<template>
  <img
    :src="src"
    :alt="alt"
    v-static-squircle="{
      width: 600,
      height: 400,
      cornerRadius: 32,
      cornerSmoothing: 0.8,
    }"
    class="object-cover"
  />
</template>

// apps/examples-svelte/src/examples/ImageContainer.svelte
<script lang="ts">
  import { staticSquircle } from "@squircle-js/svelte";

  let { src, alt } = $props<{ src: string; alt: string }>();
</script>

<img
  {src}
  {alt}
  use:staticSquircle={{
    width: 600,
    height: 400,
    cornerRadius: 32,
    cornerSmoothing: 0.8,
  }}
  class="object-cover"
/>
