// packages/svelte/src/lib/Squircle.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";

  import { squircle } from "./squircle.js";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    cornerRadius?: number;
    cornerSmoothing?: number;
    width?: number;
    height?: number;
    defaultWidth?: number;
    defaultHeight?: number;
    children?: Snippet;
  }

  let {
    cornerRadius,
    cornerSmoothing = 0.6,
    width,
    height,
    defaultWidth,
    defaultHeight,
    children,
    ...rest
  }: Props = $props();
</script>

<div
  {...rest}
  use:squircle={{
    cornerRadius,
    cornerSmoothing,
    width,
    height,
    defaultWidth,
    defaultHeight,
  }}
>
  {@render children?.()}
</div>

// packages/vue/src/Squircle.vue
<script setup lang="ts">
import { ref } from "vue";
import { useSquircle, type UseSquircleOptions } from "./useSquircle";

defineOptions({ inheritAttrs: true });

const props = withDefaults(defineProps<UseSquircleOptions>(), {
  cornerSmoothing: 0.6,
});

const el = ref<HTMLDivElement | null>(null);

useSquircle(el, () => ({
  cornerRadius: props.cornerRadius,
  cornerSmoothing: props.cornerSmoothing,
  width: props.width,
  height: props.height,
  defaultWidth: props.defaultWidth,
  defaultHeight: props.defaultHeight,
}));
</script>

<template>
  <div ref="el">
    <slot />
  </div>
</template>
