// apps/examples-solid/src/pages/list-of-squircles.tsx
import { render } from "solid-js/web";
import { TagList } from "../examples/ListOfSquircles";
import "../styles.css";

const tags = [
  { id: "1", label: "Design" },
  { id: "2", label: "Solid" },
  { id: "3", label: "Squircle" },
  { id: "4", label: "iOS" },
  { id: "5", label: "Smooth" },
];

render(() => <TagList tags={tags} />, document.getElementById("app")!);

// apps/examples-svelte/src/pages/list-of-squircles.svelte
<script lang="ts">
  import ListOfSquircles from "../examples/ListOfSquircles.svelte";

  const tags = [
    { id: "1", label: "svelte" },
    { id: "2", label: "runes" },
    { id: "3", label: "squircle" },
    { id: "4", label: "design" },
    { id: "5", label: "ios" },
    { id: "6", label: "ui" },
  ];
</script>

<ListOfSquircles {tags} />
