// apps/examples-svelte/src/examples/ListOfSquircles.svelte
<script lang="ts">
  import { staticSquircle } from "@squircle-js/svelte";

  type Tag = { id: string; label: string };

  let { tags } = $props<{ tags: Tag[] }>();
</script>

<div class="flex flex-wrap gap-2">
  {#each tags as tag (tag.id)}
    <div
      use:staticSquircle={{
        width: 80,
        height: 28,
        cornerRadius: 8,
        cornerSmoothing: 0.6,
      }}
      class="bg-sky-100 text-sky-800 text-xs font-medium flex items-center justify-center"
    >
      {tag.label}
    </div>
  {/each}
</div>

// apps/examples-solid/src/examples/ListOfSquircles.tsx
import { For } from "solid-js";
import { StaticSquircle } from "@squircle-js/solid";

type Tag = { id: string; label: string };

export function TagList(props: { tags: Tag[] }) {
  return (
    <div class="flex flex-wrap gap-2">
      <For each={props.tags}>
        {(tag) => (
          <StaticSquircle
            width={80}
            height={28}
            cornerRadius={8}
            cornerSmoothing={0.6}
            class="bg-sky-100 text-sky-800 text-xs font-medium flex items-center justify-center"
          >
            {tag.label}
          </StaticSquircle>
        )}
      </For>
    </div>
  );
}
