// apps/examples-solid/src/examples/ReactiveSquircle.tsx
import { Squircle } from "@squircle-js/solid";
import { createSignal } from "solid-js";

export function Adjustable() {
  const [radius, setRadius] = createSignal(16);

  return (
    <div class="flex items-center gap-4">
      <input
        max="64"
        min="0"
        onInput={(e) => setRadius(Number(e.currentTarget.value))}
        type="range"
        value={radius()}
      />
      <Squircle class="h-32 w-32 bg-emerald-500" cornerRadius={radius()} />
    </div>
  );
}

// apps/examples-vue/src/examples/ReactiveSquircle.vue
<script setup>
import { ref } from "vue";
import { Squircle } from "@squircle-js/vue";

const radius = ref(16);
</script>

<template>
  <div class="flex items-center gap-4">
    <input type="range" min="0" max="64" v-model.number="radius" />
    <Squircle :corner-radius="radius" class="w-32 h-32 bg-emerald-500" />
  </div>
</template>
